name: CI Build

env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    DOTNET_VERSION: "3.1.x"

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install dependencies
      run: dotnet restore ./src/HAEventHub.sln
    - name: Build
      run: dotnet build ./src/HAEventHub.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./src/HAEventHub.sln --no-restore --verbosity normal
    - name: Publish Function App
      run: dotnet publish ./src/EventHubMerge/EventHubMerge.csproj --configuration Release --output ${{ env.OUTPUT_PATH }}
    - name: Zip Function App
      shell: pwsh
      run: Compress-Archive -Path "${{ env.OUTPUT_PATH }}/*" -DestinationPath "${{ env.OUTPUT_PATH }}/EventHubMerge.zip"
    - name: Automatic Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{ env.OUTPUT_PATH }}/EventHubMerge.zip